#ifndef COMMON_H
#define COMMON_H

enum Gesture {GEST_CLICKDRAG, GEST_LINKAGE};
enum SelectionMode {SEL_NEW, SEL_INTERSECT, SEL_UNION, SEL_DIFF, SEL_REMOVE};
enum GraphDispMode {DISP_GRAPH, DISP_PINWEIGHTS, DISP_PARTITIONS};
enum FiberOp {OP_NAV, OP_SEL};
enum ColorMode {COLOR_DIR, COLOR_CLUSTER, COLOR_ATLAS_CLUSTER, COLOR_SEED, COLOR_TC};
enum FibDispMode {DISP_FIBERS, DISP_CLUSTER_CENTERS, DISP_MATCHINGS};

#endif
